version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: copywriter_learning_app_production
      POSTGRES_USER: copywriter_learning_app
      POSTGRES_PASSWORD: copywriter_learning_password
    ports:
      - "5432:5432"

  web:
    image: copywriter-learning-app:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://copywriter_learning_app:copywriter_learning_password@db/copywriter_learning_app_production
      POSTGRES_DB: copywriter_learning_app_production
      POSTGRES_USER: copywriter_learning_app
      POSTGRES_PASSWORD: copywriter_learning_password

volumes:
  postgres_data:
